### ISSUE TITLE
Merge core projects

### ISSUE THREAD

**Issue by emgarten** [NuGet/Client.Engineering#1]
Merge core projects together

•	NuGet.Client  (Single file that drives NuGet.ContentModel)
o	Merge into NuGet.Packaging
•	NuGet.Protocol.Core.Types, NuGet.Protocol.Core.V3, NuGet.Protocol.VisualStudio, NuGet.Repositories
o	Merge all four projects into a single NuGet.Protocol project
•	NuGet.Packaging.Core.Types
o	Merge into NuGet.Packaging.Core
•	NuGet.Packaging
o	Add dependencies on nuget.contentmodel and nuget.runtimemodel. Currently packaging only supports reading assets for packages.config, but it should move towards handling everything
•	NuGet.DependencyResolver.Core
o	Rename to NuGet.DependencyResolver 
•	Test helper projects (there are at least 5)
o	These should all be merged into two projects. One for core and one for desktop. The desktop project will depend on the core project and will be the super set. 
o	Test projects will depend on all product code and be high level. This will eliminate the need for having a test helper project for every project. Examples of unnecessary projects: NuGet.DependencyResolver.Core.Tests.Utility, NuGet.Commands.Test.Utility

**Comment by emgarten** [comment]
Rename VisualStudio.Facade to VisualStudio.Common

**Comment by nkolev92** [comment]
Dup of https://github.com/NuGet/Client.Engineering/issues/11 ?

**Comment by emgarten** [comment]
@nkolev92 that one is for non-core projects, the list still needs to be determined there.

**Comment by nkolev92** [comment]
I thought we dropping the distinction of "core" and "clients" project :)
Might've been simpler to have 1 issue/ 1 dev do both :)
