### ISSUE TITLE
Move test suite execution from TeamCity into VSO release definition

### ISSUE THREAD

**Issue by dtivel** [NuGet/Client.Engineering#66]

**Comment by rohit21agrawal** [comment]
One thing to keep in mind here is that release definitions don't allow you to download source code.

**Comment by dtivel** [comment]
Can you elaborate on this?  Are you talking about syncing a repository, as like the precursor to building?

**Comment by rohit21agrawal** [comment]
yeah. basically a release definition doesn't have built-in functionality to download source code for a repository.

**Comment by dtivel** [comment]
Why would you need it from a release definition?

**Comment by rohit21agrawal** [comment]
don't necessarily need it. but running unit tests become easier in our repo if we have the source since it's just  a matter of calling a msbuild target.

**Comment by dtivel** [comment]
If we want to move to DDITLabs' new DTL lab for test execution (#68), then tests must be runnable from the build drop alone.

**Comment by rohit21agrawal** [comment]
this has been completed as of today!
